torch/image

README.md
generic/image.c
init.lua
test/test_rotate.lua

```lua
image.rotate([dst,], src, theta, [mode]) 
```
Variable `mode` specifies type of interpolation to be used. *simple* or *bilinear*.
*simple* by default  (backward compatible)

Add bilinear mode for rotate()

---

init.lua

without copy display changes value of inputs: 
```lua
require 'image'
fabio = image.fabio()
print(fabio:max())  -----> 0.9843137254902
image.display(fabio)
print(fabio:max())  -----> 1
image.display{ image=fabio, saturate=false, min = 0.5, max = 0.8}
print(fabio:max())  -----> 1.6666666666667
```

copy input before display to preserve the values

---

generic/image.c

but  OpenMP is disabled in this package.

fix missing private variable in image.scale

---

README.md
generic/image.c
init.lua

This PR adds image.polar() to perform a polar transform on an image. The code supports both nearest-neighbor and bilinear interpolation. I have also added a switch that allows for using transforming only the inner circle of the image, or transforming the full image (which implies the image is padded).

Add polar transform

---

generic/image.c
image.c
init.lua
test/test_conversion.lua

* maps sRGB to linear RGB before conversion to XYZ (it follows this [wikipedia page](http://en.wikipedia.org/wiki/SRGB))
* includes a test for back and forth conversion stability
* removed old rgb2lab function which had several issues. In particular, a [commit](https://github.com/torch/image/commit/373d5036941082c6fe5ba0a9c72d9c1eb797ce1b) introduced an important regression by ignoring the [input](https://github.com/torch/image/blob/master/init.lua#L1287).

added sRGB <-> Lab conversion

---

init.lua

This reverts commit 3bc649ac0258936dfc67e5de8320faed649b6bf8.
As discussed in issue #49.

Revert "toDisplayTensor : input is only copied when necessary"

---

README.md
init.lua

Allows for specifying a result tensor to image.gaussian and image.gaussian1D.

image.gaussian result tensor

---

generic/jpeg.c
generic/png.c
png.c

In the current codebase, exceptions in working with jpg or png images are often handled by program termination. The proposed change replaces those returns/aborts with lua errors. The advantage is that lua code can catch the exceptions by pcall() and react properly.

JPG and PNG: Aborts replaced with lua errors

---

README.md
generic/image.c
init.lua
test/test_flip.lua

The c function doesn't support in-place flips, but I check for this condition in the C code.  I'm using this for a scientific application, however you could also use it to swap RGB -> BGR which might be handy for some folks:
```lua
im = image.lena()
image.display(im)
image.display(image.flip(im, 1))  -- Swap R with B chan
```

Added flip function (to a tensor up to 5D along an arbitrary dimension).

---

generic/jpeg.c
init.lua

For smaller images, this gives a healthy 10% improvement in loading time.
We are now mostly bounded by libjpeg, only 25% of the time is being spent in transposing the layout from HWD to DHW

more perf for jpeg decoder, made static loops for 1,3 channel cases

---

init.lua

Thanks to @Atcold for suggesting this.
This is a temporary fix.  It certainly can't go back to not having the assert but someone will need to fix it eventually.

modifed h/vflip assert to only check if 2D tensors are contiguous (maintaining backward compat.)

---

init.lua
test/test_gaussianpyramid.lua

Non-default tensor types as input to gaussian pyramid produce errors.
```lua
require 'image'
image.gaussianpyramid(torch.rand(8, 8), {0.5})  -- no error
image.gaussianpyramid(torch.rand(8, 8):float(), {0.5})  -- error
```

image.gaussianpyramid non-default type input fix

---

README.md
generic/image.c
init.lua
test/test_scale.lua

* Added 'bicubic' method to image.scale.
* Added unit tests of scaling.
Does interpolation for both upsizing and downsizing and does not preserve the
average pixel intensity. Note this is different from 'bilinear' which preserves
the average pixel intensity on downsizing but not on upsizing.
At edges the missing data is added by extending the first/last line segment.

Add bicubic interpolation to image.scale.

---

init.lua
test/test_decompress_jpg.lua

All test files pass and I manually tested saving PPM, PGM, PNG, JPG images in ByteTensors.

Support saving torch.ByteTensor images

---

generic/png.c

moved `png_read_update_info` call to fix problem in opening 1-bit png on mac.

fixed open 1-bit png on Mac

---

generic/image.c

This is related to commit b5fc8d0:
* `size` is 0-based (channels=0, height=1, width=2),
* `ix` and `iy` must be checked against the *source* image dimensions.

warp: fix bounds checking for bicubic mode

---

init.lua

For example, these 4-byte signatures are all valid for different variants of JPEG, e.g. JPEG/JFIF and JPEG/EXIF and various cameras' outputs:
```
FF D8 FF E0
FF D8 FF E1
FF D8 FF E3
FF D8 FF E8
FF D8 FF DB
```
So we only check the first 3 bytes.
sources:
https://en.wikipedia.org/wiki/List_of_file_signatures
http://filesignatures.net/?page=all&order=SIGNATURE&alpha=J

Fix JPEG magic number to handle more JPEGs

---

image-1.1.alpha-0.rockspec
init.lua

Using doubles when dealing with image sizes is risky.
Note that:
```lua
th> return  math.floor(100/161*161)
99
```
or:
```lua
th> = math.floor(113/100*100)
112
```
This leads to unexpected results in image.scale() such as:
```lua
th> return  image.scale(image.scale(image.lena(), 113, 100), "^100"):size()
3
100
112
[torch.LongStorage of size 3]
```
or:
```lua
return  image.scale(image.scale(image.lena(), 161, 100), 161):size()
3
99
161
[torch.LongStorage of size 3]
```
This PR addresses this issue by using rational numbers instead.

fix corner-case issues when rescaling

---

doc/simpletransform.md
init.lua

format may be "c", "tl", "tr", "bl" or "br" for center, top left, top right, bottom left and bottom right, respectively.
doc added.

adding image.crop([dst,] src, format, width, height)

---

generic/image.c
test/test_scale.lua

Bicubic interpolation was not working for scaling torch.ByteTensors.
* Temporary variables were also uint8, made them doubles.
* Added unit tests for ByteTensors.

Fix bug with image.scale 'bicubic' and ByteTensors.

---

init.lua

This fixes a bug where `decompress()` returns an uninformative error when an input `tensor` is very small or empty Tensor.

Fix bug when empty / too small tensor is provided to decompress()

---

test/test.lua

Requiring image previously switched the default tensor type to DoubleTensor.

image test: preserve default tensor type.

---

generic/image.c

The tests all pass (although tests in image are pretty bare-bones).
Someone with more OpenMP experience please check it (i.e. variables declared on the stack (in the loop) are made thread-private by default right?).
For bicubic warp I get about 10x speed up using 12 cores on a 256x256 image.

add openMP pragma to warp, hflip (non-inplace) and vflip (non-inplace).

---

generic/image.c
image.c
init.lua
test/test.lua

Summary
=======
In generic/image.c many of the intermediate calculations are done using the
datatype `real`. For `ByteTensor`s this is an integral type meaning that undesired
results are obtained for `ByteTensor`s.
The following methods are fixed for ByteTensors:
*   y2jet
*   rgb2y
*   rgb2hsv
*   hsv2rgb
*   rgb2hsl
*   hsl2rgb
*   gaussian
The following methods are disabled for ByteTensors:
*   rgb2lab
*   lab2rgb
The following methods are believed to be fixed for ByteTensors, but have not
been tested:
*   warp
*   rotate
*   polar
The following methods have not been functionally modified, are believed to
already work for ByteTensors, but have not been tested:
*   crop
*   translate
*   vflip
*   hflip
*   flip
Changes
=======
generic/image.c
---------------
*   Define a `temp_t` type …

Fix issues with ByteTensors.

---

init.lua

This speeds up calls to image.crop that don't pass a dst image

Only scale output in image.crop if dst is provded

---

init.lua

To solve #129 and problems like soumith/imagenet-multiGPU.torch#43.
I kept the old detection via the extension, but it should never been called (except for exotic JPEG files?). Of course we can as well remove it.
UPDATE: keeping the old detection is handy precisely if someones loads a non supported format, e.g.:
```
> image.load("test.gif")
<image.load> unknown image type: gif
```

load: use magic number to detect image format

---

generic/ppm.c

Apart from this minor PR, note that I faced this problem while re-installing and running tests (that failed / seg. faulted because of missing assets). LuaRocks install logs indicated that:
```
-- Installing: /path/to/torch/install/lib/luarocks/rocks/image/1.1.alpha-0/lua/image/assets/lena.jpg
[...]
Warning: /path/to/torch/install/share/lua/5.1/image/assets/lena.jpg is not tracked by this installation of LuaRocks. Moving it to /path/to/torch/install/share/lua/5.1/image/assets/lena.jpg~~~
```
First time ever I encountered this. Plus: it sounds like there is a race or something because it is not reproducible.
So the question is: is it the right way to do to install asset files on behalf of LuaRocks like [here](https://github.com/torch/image/blob/0013b8c4ac71eda9793159caddb906d6f495482b/CMakeL …

ppm: raise an error if fopen failed

---

test/test.lua

also: the corrupted PNG test was invalid because `getTestImagePath` was missing.

test: switch to assertError

---

init.lua

Loading the sys package can cause a deadlock in some OpenBLAS
configurations when multiple Torch threads require sys (such as via the
image package) at the same time.
Depends on torch/sys#8

Only require sys.fpath from sys

---

generic/image.c

The bicubic interpolation code accesses non-allocated memory when `src_len` is 1 because it doesn't have a special case like bilinear interpolation does. This PR addresses that bug.
I ran the following test to confirm it works:
```
require 'image'
im = torch.randn(3, 2, 3):float()
for n = 1,1000 do resim = image.scale(im, 256, 768, 'bicubic') end
```

Fix bicubic interpolation when source has size 1

---

init.lua

If height or width is less than one after the resize, the output tensor would have the wrong number dimensions (2 or 1 instead of 3).
Before:
```lua
image.scale(torch.rand(3,3,600),100):size()
-- the output is a tensor of size 3
```
After
```lua
image.scale(torch.rand(3,3,600),100):size()
-- the output is a tensor of size 3x1x100
```

Fix in image.scale when one of the dimensions is too small

---

test/test.lua

Before this change, the conversion from large floating point values to `unsigned char` caused undefined behaviour.

Fix double-to-byte conversion order

---

test/test_rotate.lua
test/test_warp.lua

Hi, two commits
(1) Fixes the test_warp scaling bug
(2) Fixes indentation in the rotation test script (that i verifies works correctly).
There is a mistake in `test_warp.lua`. Try a rotation of 0 degrees and you will see that it will scale ever slightly, by around one pixel. The following thing describes the problem and shows the fix of the PR:
_Do not look at the colors themselves, the .GIF format might have changed them._
Look how in the current state the geometry changes with respect to the source image. And look how the geometry stays exactly on-pixel.
Luckily little harm is done as this is a test script, but this is the real only documentation that is to be found about the warp functionality, it's good to keep it correctly. I found this bug because I was implementing the warp …

Fixes for test_warp.lua

---

doc/saveload.md

Here is a small precision about image saving.
In image.save, the tensor is first clamped between 0 and 1 before being written to the disk.
This can lead to unexpected behaviors (this was not mentioned in the doc yet) when one saves a image tensor whose values are outside this range (for instance a centered/normalized preprocessed image). See the example below :  
A solution could be to scale the tensor between 0 and 255 directly instead of clamping/scaling. 
But as this may have been done on purpose (?), and as it may cause backward-compatibility issues, I simply propose here to clarify this in the doc.

Add details about image saving in the doc

---

init.lua

Refer to #187. 
Previously the following code would've given an error:
```
require 'torch'
require 'init'
torch.setdefaulttensortype('torch.FloatTensor')
local im = image.lena()
local matrix = torch.Tensor({{1,0.5},{0,1}}):double()
local im2 = image.affinetransform(im,matrix,'bilinear')
local fld = torch.zeros(2, 512, 512):double()
local im2 = image.warp(im,fld,'bilinear')
```
This seems to be because `src.image.warp` expects field to be of default tensor type. This issue is fixed by coercing passed matrix or field to default tensor type.

Fixed tensor type issue in affinetransform and warp

---

init.lua
test/test_warp.lua

PR #189 introduced fixing of the `field` variable to that of the torch's default type.
If it should have been casted at all, it should be casted to that of the image's input type, to circumvent the type-similarity issue not being thrown.
I have decided to remove this cast introduced in #189 altogether, making it the developers responsibility to cast and use correct and matching types.
I have also added a few lines of tests in `test_warp.lua` to make sure this issue does not re-occur:
```lua
out = image.warp(im:float(), mtx:float(), 'bilinear') -- both float
out = image.warp(im:double(), mtx:double(), 'bilinear') --both double
```
And do note mixing will throw a proper error
```lua
out = image.warp(im:float(), mtx:double(), 'bilinear') -- fails with crystal clear type error
out = …
```

Fixes warp type-cast issue in #189

---

generic/image.c

`drawRect` throws error when `lineWidth>1` and a pixel coordinate of the rectangle is out of the image boundary. e.g., the following code could not succeed
```
image = require 'image'
bg = torch.ByteTensor(3, 100, 100):fill(3)
img = image.drawRect(bg, 0, 80, 50, 99, {color={255, 0, 255}, lineWidth=5})
image.save('test.png', img)
```
which throws error:
```
/scratch0/torch/install/share/lua/5.1/image/init.lua:2172: bad argument #2 to 'drawRect' (out of range at /tmp/luarocks_torch-scm-1-3526/torch7/lib/TH/generic/THTensor.c:759)
stack traceback:
[C]: at 0x7f9ca8b008e0
[C]: in function 'drawRect'
/scratch0/torch/install/share/lua/5.1/image/init.lua:2172: in function 'drawRect'
/scratch0/image/test.lua:3: in main chunk
```
After this fix, the same code could generate rectangles on top of the …

Fix out-of-boundary bug when lineWidth is big

---

init.lua

All other PNG calls require 'liblua_png' and the test currently
fails on compression.

compressPNG should require 'liblua_png' rather than 'libpng'.
