torch/image

README.md
generic/jpeg.c
init.lua
test/test_compress_jpg.lua

Also added documentation for it and a unit test.

Added docs for decompressJPG.  Added compressJPG function.

---

generic/jpeg.c

This speeds up JPEG decoding (both in-memory decompressJPG as well as image.load) by about 2x or more.
Decoding Lena on my macbook:
OLD:
2.005 sec, 128 images, 0 workers, 63.85 decoded/sec
NEW:
0.858 sec, 128 images, 0 workers, 149.12 decoded/sec

jpeg decoding optimizations. removing bound checks

---

init.lua

fixing y2jet for other default tensor types

---

generic/image.c
init.lua

rgb2y for byte tensors (needed to go into C for efficiency)

---

generic/jpeg.c

This overrides libjpeg's `output_message` so that messages are no more
written on stderr but directly returned via `luaL_error`.
This is related to #58 and #59.

jpeg.c: raise libjpeg error message on size/load

---

generic/image.c

Avoid recomputing sin/cos in rotate main loop

---

generic/image.c

fixes #73 and corner case from #86

fixing scale bugs in bilinear (src = 1) and bicubic (dest = 1)

---

README.md
generic/image.c
init.lua
test/test_warp.lua

A simple change to warp so that the user can specify the pad value when interpolating off the image.

Added user specified pad value to warp function.

---

init.lua

Fix clampImage function call to saturate

---

generic/png.c

This brings more informative error messages (e.g. see #97) and no more clutter `stderr`.
Warnings are still written to `stderr` via the default libpng handler (I thought it was better not to silent them out).

png.c: bubble up error messages from libpng

---

doc/colorspace.md
doc/gui.md
doc/index.md
doc/paramtransform.md
doc/saveload.md
doc/simpletransform.md
doc/tensorconstruct.md
mkdocs.yml

This PR will allow us to have this : http://image.readthedocs.org/en/rtd/index.html . 
To make it look nice, I divided the README.md into different files.
It still allows for the docs to be read from github.

readthedocs

---

generic/image.c

Fix boundary/quantization artefacts on rotation.

---

generic/image.c

The existing bicubic sampling produces artifacts. Fixes issue #103

Fix bicubic interpolation in image.warp

---

test/test.lua

Some of the newer tests in test_scale got lost in the reconciliation of the
tests.
* Restored lost test_scale.lua tests
* Ensured that tests still run (with a warning) if graphicsmagick is missing.

Restore tests lost in commit 03e65a.

---

init.lua

for given window to display, make sure the window is visible

check given window visible

---

test/test.lua

- tensors with same content but different dimensions
- assert should only be used for boolean conditions
See torch/torch7#562

test: fix torch.Tester warnings

---

generic/png.c

The [PNG manual](http://www.libpng.org/pub/png/libpng-1.2.5-manual.html) shows how to clean up after `setjmp(png_jmpbuf(...))`. We were missing the cleanup.

[generic/png.c] Add missing error handling

---

doc/paramtransform.md
init.lua

I have implemented affine transformation with the help of `image.warp`.

Added affinetransform 

---

generic/image.c

Cast 255 to 255.0f in drawPixel
Fix https://github.com/torch/image/issues/190

Fix Problem drawing colors in drawText

---

doc/saveload.md
generic/ppm.c
init.lua

Add getPPMsize and getPGMsize functions
Combine them with getPNGsize and getJPGsize for getSize function

Add image.getSize(filename) function

---

generic/png.c
init.lua
png.c
test/test.lua

Hello, 
I added function to compress an image into PNG in-memory format, similar to compressJPG

Added code to compress tensor into PNG in-memory similar to compressJPG
